### ISSUE TITLE
Move setup code inside a check for is_user_logged_in()?

### ISSUE THREAD

**Issue by danbleile** [washingtonstateuniversity/WSUWP-Plugin-A11y-Status#1]
https://github.com/washingtonstateuniversity/WSUWP-Plugin-A11y-Status/blob/ce95b04814597cb71e65a39ff7c4caeb78139c31/wsuwp-a11y-status.php#L25

Just a take-it or leave-it thought... It looks like most of this code is designed to execute only if the user is logged in. It might be worthwhile to to a check early if the user is logged in or even look for specific capabilities (so you aren't checking against subscribers) before loading any assets or executing code.

**Comment by admturner** [comment]
That's a good idea, since this should only function when a user is logged in to the admin area. I experimented with only loading the plugin when a user is logged in -- and with loading it in the admin area only -- but ran into errors from both now that the plugin hooks onto the `wp_login` action.

I think it throws an error if the plugin loader is gated behind an "is user logged in" or "is admin" condition because the `user_login` hook fires before either of those conditions is set, causing the plugin to load in too late for the login hook. For now it looks like it might be easiest to stick with capability checks as-needed in the plugin methods.
